"""
export_c.py -- dump the mel filterbank, DCT matrix, and Hann window as C
arrays (Step 2), and later the quantized model (Step 8).

export_mel_filterbank() writes config.C_MEL_HEADER_NAME to config.EXPORT_DIR.
It carries a generated banner naming every frozen config value it was built
from, plus #define constants for the shapes and config.FEATURE_CONTRACT_HASH
as a string. The firmware is expected to static_assert its own local
constants against that string at build time -- that's the entire reason
FEATURE_CONTRACT_HASH exists: a drift between the Python front end and the
firmware becomes a compile-time failure, not a silently wrong detector.

export_model() (Step 8) will dump a trained, quantized .tflite as a byte
array into config.C_HEADER_NAME. Not implemented yet -- there is no model.
"""

from __future__ import annotations

import datetime as _dt

import numpy as np

import config
import features


# =============================================================================
# Formatting helpers
# =============================================================================

def c_identifier(name: str) -> str:
    """config.C_PREFIX + a C-safe identifier."""
    safe = "".join(ch if ch.isalnum() else "_" for ch in name)
    if safe[:1].isdigit():
        safe = "_" + safe
    return f"{config.C_PREFIX}{safe}"


def format_banner(source_module: str) -> str:
    """Comment block naming the frozen config values baked into this header.

    No timestamp inside the hashed contract itself (that would make the
    contract hash non-deterministic); the generation time is informational
    only, in the banner, outside anything that's compared.
    """
    generated = _dt.datetime.now().isoformat(timespec="seconds")
    lines = [
        "/*",
        f" * Auto-generated by {source_module} -- DO NOT EDIT BY HAND.",
        f" * Generated: {generated}",
        f" * Feature contract hash: {config.FEATURE_CONTRACT_HASH}",
        " *",
        " * Regenerate with:",
        f" *     python {source_module}",
        " *",
        " * If this hash does not match KWS_FEATURE_CONTRACT_HASH in the",
        " * firmware's own config, the Python front end and the firmware",
        " * have drifted apart -- do not trust inference output until they",
        " * match again.",
        " */",
    ]
    return "\n".join(lines)


def _format_float(x: float) -> str:
    return f"{x:.8e}f"


def dump_float_array(name: str, array: np.ndarray) -> str:
    """`static const float <name>[..] = {...};` with nested braces matching
    `array.ndim`, so multi-dimensional tables (e.g. the filterbank) stay
    indexable the same way on the C side as on the Python side.
    """
    array = np.asarray(array, dtype=np.float32)
    ident = c_identifier(name)
    dims = "".join(f"[{d}]" for d in array.shape)

    def render(sub: np.ndarray, indent: str) -> str:
        if sub.ndim == 1:
            values = ", ".join(_format_float(float(v)) for v in sub)
            return f"{indent}{{ {values} }}"
        inner = ",\n".join(render(row, indent + "    ") for row in sub)
        return f"{indent}{{\n{inner}\n{indent}}}"

    body = render(array, "")
    return f"static const float {ident}{dims} = {body};"


def dump_byte_array(name: str, data: bytes) -> str:
    """`static const unsigned char <name>[] = {...};`, 16 bytes per line.

    Used for the quantized tflite flatbuffer in Step 8. tflite interpreters
    generally want this 4-byte (some want 16-byte) aligned in the final
    binary -- that's a linker/attribute concern for the firmware side, not
    something this dump can guarantee, so the firmware header should apply
    its own `alignas`/section attribute to the emitted array.
    """
    ident = c_identifier(name)
    hex_bytes = [f"0x{b:02x}" for b in data]
    lines = [
        ", ".join(hex_bytes[i:i + 16]) for i in range(0, len(hex_bytes), 16)
    ]
    body = ",\n    ".join(lines)
    return (
        f"static const unsigned char {ident}[{len(data)}] = {{\n"
        f"    {body}\n"
        f"}};"
    )


# =============================================================================
# Step 2: feature tables
# =============================================================================

def export_mel_filterbank() -> None:
    """Write config.C_MEL_HEADER_NAME: filterbank, DCT matrix, Hann window,
    plus the #define constants a firmware build needs to size its buffers
    and to assert the contract hash.
    """
    config.EXPORT_DIR.mkdir(parents=True, exist_ok=True)
    out_path = config.EXPORT_DIR / config.C_MEL_HEADER_NAME
    guard = out_path.stem.upper().replace("-", "_") + "_H_"

    filterbank = features.build_mel_filterbank()
    dct_matrix = features.build_dct_matrix()
    window = features.window_fn()

    defines = "\n".join([
        f"#define KWS_SAMPLE_RATE        {config.SAMPLE_RATE}",
        f"#define KWS_FRAME_LEN          {config.FRAME_LEN}",
        f"#define KWS_STRIDE_LEN         {config.STRIDE_LEN}",
        f"#define KWS_NFFT               {config.NFFT}",
        f"#define KWS_NUM_FREQ_BINS      {config.NUM_FREQ_BINS}",
        f"#define KWS_NUM_MEL            {config.NUM_MEL}",
        f"#define KWS_NUM_MFCC           {config.NUM_MFCC}",
        f"#define KWS_NUM_FRAMES         {config.NUM_FRAMES}",
        f'#define KWS_FEATURE_CONTRACT_HASH "{config.FEATURE_CONTRACT_HASH}"',
    ])

    sections = [
        format_banner("export_c.py"),
        "",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        defines,
        "",
        dump_float_array("mel_filterbank", filterbank),
        "",
        dump_float_array("dct_matrix", dct_matrix),
        "",
        dump_float_array("hann_window", window),
        "",
        f"#endif  /* {guard} */",
        "",
    ]

    out_path.write_text("\n".join(sections), encoding="utf-8")
    print(f"wrote {out_path}  ({out_path.stat().st_size} bytes)")
    print(f"  mel_filterbank  {filterbank.shape}")
    print(f"  dct_matrix      {dct_matrix.shape}")
    print(f"  hann_window     {window.shape}")


# =============================================================================
# Step 8: quantized model (not yet -- no trained model exists)
# =============================================================================

def export_model(tflite_path) -> None:
    """Write config.C_HEADER_NAME from a quantized .tflite file."""
    raise NotImplementedError("Step 8")


def main() -> None:
    print(config.summary())
    print()
    export_mel_filterbank()


if __name__ == "__main__":
    main()
