"""
make_test_vectors.py -- produces the 3 test clips for the Step 2 firmware
parity test (the spec's "gating step").

Isolates math bugs from mic/acoustic issues: the firmware should read the
raw int16 samples straight out of a hardcoded C array, not from a mic or a
speaker -- so a parity failure can only be a math bug, never acoustics.

data/positives/ is still empty (pending real recordings), so these 3 clips
are synthetic: a pure tone, silence, and white noise. That's fine for this
test -- it's exercising the *math* of the feature pipeline, not asking
"does this sound like the keyword."

For each clip, writes to kws/test_vectors/:
    <name>.wav                 16 kHz mono int16 (for reference / for
                                playing manually later if you also want to
                                test the acoustic path)
    <name>_input.h             the same raw int16 samples as a C array --
                                firmware #includes this directly, no wav
                                parsing needed on device
    <name>_mfcc_reference.npy  Python's extract_mfcc() output, (49, 10) f32
    <name>_mfcc_reference.csv  same, human-readable, same layout
                                check_parity.py expects from a firmware dump

Run:
    python make_test_vectors.py

Then hand test_vectors/*_input.h to the firmware side, get their dumped
MFCC output back, and run check_parity.py against it.
"""

from __future__ import annotations

import wave
from pathlib import Path

import numpy as np

import config
import features
from export_c import c_identifier, format_banner

OUT_DIR = config.ROOT / "test_vectors"


# =============================================================================
# The 3 clips
# =============================================================================

def _tone(freq_hz: float = 440.0, amplitude: float = 0.5) -> np.ndarray:
    t = np.arange(config.CLIP_SAMPLES) / config.SAMPLE_RATE
    wave_f = amplitude * np.sin(2.0 * np.pi * freq_hz * t)
    return (wave_f * 32767.0).astype(np.int16)


def _silence() -> np.ndarray:
    return np.zeros(config.CLIP_SAMPLES, dtype=np.int16)


def _white_noise(amplitude: float = 0.2) -> np.ndarray:
    rng = np.random.default_rng(config.SEED)
    wave_f = rng.uniform(-amplitude, amplitude, config.CLIP_SAMPLES)
    return (wave_f * 32767.0).astype(np.int16)


def build_clips() -> dict[str, np.ndarray]:
    return {
        "tone_440hz": _tone(),
        "silence": _silence(),
        "white_noise": _white_noise(),
    }


# =============================================================================
# Output writers
# =============================================================================

def write_wav(path: Path, samples: np.ndarray) -> None:
    with wave.open(str(path), "wb") as f:
        f.setnchannels(1)
        f.setsampwidth(2)
        f.setframerate(config.SAMPLE_RATE)
        f.writeframes(samples.astype("<i2").tobytes())


def dump_int16_array(name: str, samples: np.ndarray) -> str:
    """`static const int16_t <name>[] = {...};`, 16 values per line."""
    ident = c_identifier(name)
    values = [str(int(v)) for v in samples]
    lines = [", ".join(values[i:i + 16]) for i in range(0, len(values), 16)]
    body = ",\n    ".join(lines)
    return (
        f"static const int16_t {ident}[{len(values)}] = {{\n"
        f"    {body}\n"
        f"}};"
    )


def write_input_header(path: Path, clip_name: str, samples: np.ndarray) -> None:
    text = "\n".join([
        format_banner("make_test_vectors.py"),
        "",
        "#include <stdint.h>",
        "",
        f"#define KWS_TEST_{clip_name.upper()}_LEN {len(samples)}",
        "",
        dump_int16_array(f"test_{clip_name}_input", samples),
        "",
    ])
    path.write_text(text, encoding="utf-8")


def write_readme(path: Path, clip_names: list[str]) -> None:
    names = "\n".join(f"  - `{n}`" for n in clip_names)
    text = f"""\
# test_vectors/

Step 2 firmware parity fixtures. Generated by `make_test_vectors.py` --
regenerate rather than hand-edit.

Clips:
{names}

Each clip has 4 files:

| File | Purpose |
|---|---|
| `<name>.wav` | 16 kHz mono int16, for reference / manual playback |
| `<name>_input.h` | the same samples as a C array -- feed this straight into the firmware's `extract_mfcc` equivalent, no wav parsing, no mic |
| `<name>_mfcc_reference.npy` | Python's `extract_mfcc()` output, float32 (49, 10) |
| `<name>_mfcc_reference.csv` | same, human-readable, 49 lines x 10 values |

## Running the parity check

1. Build the firmware's MFCC extractor against `<name>_input.h`.
2. Have it print its `(49, 10)` output over serial as 49 comma-separated
   lines (same layout as the `.csv` reference).
3. Save that dump to a file, then:

```bash
python check_parity.py tone_440hz path/to/esp32_dump.csv
python check_parity.py silence path/to/esp32_dump.csv
python check_parity.py white_noise path/to/esp32_dump.csv
```

Done when all 3 print `PASS` (max abs diff < 0.05). Do the hardcoded-array
version first, always -- it isolates math bugs from mic/acoustic issues.
Only after that passes is it worth testing the same clips played through a
speaker into the real mic.
"""
    path.write_text(text, encoding="utf-8")


# =============================================================================

def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    clips = build_clips()

    for name, samples in clips.items():
        assert samples.shape == (config.CLIP_SAMPLES,), (name, samples.shape)
        assert samples.dtype == np.int16, (name, samples.dtype)

        write_wav(OUT_DIR / f"{name}.wav", samples)

        mfcc = features.extract_mfcc(samples)
        assert mfcc.shape == config.FEATURE_SHAPE, (name, mfcc.shape)
        np.save(OUT_DIR / f"{name}_mfcc_reference.npy", mfcc)
        np.savetxt(
            OUT_DIR / f"{name}_mfcc_reference.csv", mfcc, delimiter=",", fmt="%.8e"
        )

        write_input_header(OUT_DIR / f"{name}_input.h", name, samples)

        print(f"{name:12s}  wav + input.h + mfcc_reference.{{npy,csv}} written")

    write_readme(OUT_DIR / "README.md", list(clips))
    print(f"\nwrote {len(clips)} test vectors to {OUT_DIR}")


if __name__ == "__main__":
    main()
