/*
 * Auto-generated by make_firmware_bundle.py -- DO NOT EDIT BY HAND.
 * Generated: 2026-09-26T20:30:17
 * Feature contract hash: eaec172cd4689c14
 *
 * Regenerate with:
 *     python make_firmware_bundle.py
 *
 * If this hash does not match KWS_FEATURE_CONTRACT_HASH in the
 * firmware's own config, the Python front end and the firmware
 * have drifted apart -- do not trust inference output until they
 * match again.
 */
#ifndef KWS_PARITY_VECTORS_H_
#define KWS_PARITY_VECTORS_H_

#include <stdint.h>

#define KWS_PARITY_CONTRACT_HASH  "eaec172cd4689c14"
#define KWS_PARITY_CLIP_SAMPLES   16000
#define KWS_PARITY_NUM_FRAMES     49
#define KWS_PARITY_NUM_MFCC       10
#define KWS_PARITY_MFCC_TOL       0.05f   /* max abs diff, Step 2 spec */
#define KWS_PARITY_IN_SCALE       4.48252767e-01f
#define KWS_PARITY_IN_ZERO_POINT  67
#define KWS_PARITY_OUT_SCALE      1.45794585e-01f
#define KWS_PARITY_OUT_ZERO_POINT 2
#define KWS_PARITY_NUM_VECTORS    11
#define KWS_PARITY_HOP_SAMPLES    1600
#define KWS_PARITY_STREAM_WINDOWS 5
#define KWS_PARITY_THETA          0.75f
#define KWS_PARITY_K              3
#define KWS_PARITY_WINDOW         5
#define KWS_PARITY_REFRACTORY_HOPS 10

#include "vec_silence.h"
#include "vec_tone_440hz.h"
#include "vec_white_noise.h"
#include "vec_chirp_100_3800hz.h"
#include "vec_square_fullscale.h"
#include "vec_impulse.h"
#include "vec_quiet_noise_8lsb.h"
#include "vec_speech_gsc_yes.h"
#include "vec_speech_gsc_no.h"
#include "vec_go_positive_test_027.h"
#include "vec_nogo_hardneg_test_001.h"

typedef struct {
    const char    *name;
    const int16_t *input;                                  /* KWS_PARITY_CLIP_SAMPLES */
    const float  (*mfcc)[KWS_PARITY_NUM_MFCC];             /* expected MFCC [frames][coefs] */
    const int8_t  *q;                                      /* expected int8 model input, frames*coefs */
    const int8_t  *model_out_q;                            /* expected int8 model output, 3 classes */
    float          keyword_prob;                           /* expected softmax P(keyword) */
    const int16_t *stream;                                 /* go/no-go only, else 0: STREAM_WINDOWS windows, last == input */
    const float   *stream_prob;                            /* go/no-go only: expected P(keyword) per stream window */
    int            expect_fire;                            /* 1 go (must fire), 0 no-go (must not), -1 parity-only vector */
} kws_parity_vector_t;

static const kws_parity_vector_t kws_parity_vectors[KWS_PARITY_NUM_VECTORS] = {
    { "silence", kws_vec_silence_input, kws_vec_silence_mfcc, kws_vec_silence_q, kws_vec_silence_model_out_q, KWS_VEC_SILENCE_KEYWORD_PROB, 0, 0, -1 },
    { "tone_440hz", kws_vec_tone_440hz_input, kws_vec_tone_440hz_mfcc, kws_vec_tone_440hz_q, kws_vec_tone_440hz_model_out_q, KWS_VEC_TONE_440HZ_KEYWORD_PROB, 0, 0, -1 },
    { "white_noise", kws_vec_white_noise_input, kws_vec_white_noise_mfcc, kws_vec_white_noise_q, kws_vec_white_noise_model_out_q, KWS_VEC_WHITE_NOISE_KEYWORD_PROB, 0, 0, -1 },
    { "chirp_100_3800hz", kws_vec_chirp_100_3800hz_input, kws_vec_chirp_100_3800hz_mfcc, kws_vec_chirp_100_3800hz_q, kws_vec_chirp_100_3800hz_model_out_q, KWS_VEC_CHIRP_100_3800HZ_KEYWORD_PROB, 0, 0, -1 },
    { "square_fullscale", kws_vec_square_fullscale_input, kws_vec_square_fullscale_mfcc, kws_vec_square_fullscale_q, kws_vec_square_fullscale_model_out_q, KWS_VEC_SQUARE_FULLSCALE_KEYWORD_PROB, 0, 0, -1 },
    { "impulse", kws_vec_impulse_input, kws_vec_impulse_mfcc, kws_vec_impulse_q, kws_vec_impulse_model_out_q, KWS_VEC_IMPULSE_KEYWORD_PROB, 0, 0, -1 },
    { "quiet_noise_8lsb", kws_vec_quiet_noise_8lsb_input, kws_vec_quiet_noise_8lsb_mfcc, kws_vec_quiet_noise_8lsb_q, kws_vec_quiet_noise_8lsb_model_out_q, KWS_VEC_QUIET_NOISE_8LSB_KEYWORD_PROB, 0, 0, -1 },
    { "speech_gsc_yes", kws_vec_speech_gsc_yes_input, kws_vec_speech_gsc_yes_mfcc, kws_vec_speech_gsc_yes_q, kws_vec_speech_gsc_yes_model_out_q, KWS_VEC_SPEECH_GSC_YES_KEYWORD_PROB, 0, 0, -1 },
    { "speech_gsc_no", kws_vec_speech_gsc_no_input, kws_vec_speech_gsc_no_mfcc, kws_vec_speech_gsc_no_q, kws_vec_speech_gsc_no_model_out_q, KWS_VEC_SPEECH_GSC_NO_KEYWORD_PROB, 0, 0, -1 },
    { "go_positive_test_027", kws_vec_go_positive_test_027_input, kws_vec_go_positive_test_027_mfcc, kws_vec_go_positive_test_027_q, kws_vec_go_positive_test_027_model_out_q, KWS_VEC_GO_POSITIVE_TEST_027_KEYWORD_PROB, kws_vec_go_positive_test_027_stream, kws_vec_go_positive_test_027_stream_prob, KWS_VEC_GO_POSITIVE_TEST_027_EXPECT_FIRE },
    { "nogo_hardneg_test_001", kws_vec_nogo_hardneg_test_001_input, kws_vec_nogo_hardneg_test_001_mfcc, kws_vec_nogo_hardneg_test_001_q, kws_vec_nogo_hardneg_test_001_model_out_q, KWS_VEC_NOGO_HARDNEG_TEST_001_KEYWORD_PROB, kws_vec_nogo_hardneg_test_001_stream, kws_vec_nogo_hardneg_test_001_stream_prob, KWS_VEC_NOGO_HARDNEG_TEST_001_EXPECT_FIRE }
};

#endif  /* KWS_PARITY_VECTORS_H_ */
