/*
 * Auto-generated by make_firmware_bundle.py -- DO NOT EDIT BY HAND.
 * Generated: 2026-09-26T20:30:17
 * Feature contract hash: eaec172cd4689c14
 *
 * Regenerate with:
 *     python make_firmware_bundle.py
 *
 * If this hash does not match KWS_FEATURE_CONTRACT_HASH in the
 * firmware's own config, the Python front end and the firmware
 * have drifted apart -- do not trust inference output until they
 * match again.
 */
/* Front-end constants that features.py uses but kws_mel_filterbank.h does not
 * carry. Generated from config.py -- all of them are inside the contract hash. */
#ifndef KWS_FRONTEND_CONSTANTS_H_
#define KWS_FRONTEND_CONSTANTS_H_

#define KWS_PREEMPHASIS    0.97f    /* y[0] = x[0]; y[n] = x[n] - PRE*x[n-1], over the WHOLE 1 s clip */
#define KWS_LOG_MEL_FLOOR  1e-06f  /* log(mel_energy + FLOOR), natural log */
#define KWS_INT16_SCALE    32768.0f  /* x = pcm / 32768 (so -32768 -> -1.0) */

#endif
